### ISSUE TITLE
When the state is a reference type stored in an array, it cannot be obtained when modifying

### ISSUE THREAD

**Issue by cs-storm** [immerjs/use-immer#116]
When the state is a reference type stored in an array, the value in the member object cannot be directly obtained from the parameter.
```tsx
// When I use immer
const [tags, setTags] = useImmer([{a:1}]);

setTags(item => {
  item.forEach(t => {
    console.log(t); // Proxy(Object)
  })
})

// When I use state
const [tags, setTags] = useState([{a:1}]);

setTags(item => {
  item.forEach(t => {
    console.log(t);// {a: 1}
  })
  return []
})
```

**Comment by mweststrate** [comment]
You can programatically access `t` just fine. How Proxies are displayed in your log depends on the JS runtime you use. You can pass it through `JSON.stringify` to get a consistent representation.

**Comment by cs-storm** [comment]
What if I want to use the findIndex method? Using immer doesn't seem to work properly.

**Comment by mweststrate** [comment]
https://github.com/immerjs/immer/issues/new/choose and follow the template

**Comment by cs-storm** [comment]
> https://github.com/immerjs/immer/issues/new/choose and follow the template

I just tried it and there is no problem. It should be that I made other mistakes before. Thank you for your reply.
