### ISSUE TITLE
Incorrect immer peer dependency

### ISSUE THREAD

**Issue by ambar-arkin** [immerjs/use-immer#127]
Immer peer dependency is set to >=2
https://github.com/immerjs/use-immer/blob/b07fdfcefccfc7ff4252d52d58493d443a63d4c2/package.json#L43

But the library depends on `freeze` function which is only available in >=8.
This causes error when using with 2.x version:
```
Error: Uncaught [TypeError: e.freeze is not a function]
```

Can immer 2.x still be supported by conditionally freezing only if the function exists?

**Comment by mweststrate** [comment]
Fixed in 0.10.0
