### ISSUE TITLE
vscode auto import

### ISSUE THREAD

**Issue by minhquan1313** [immerjs/use-immer#129]
Usually when I type out some hook or function, I will get suggestion. Like this:
![image](https://github.com/immerjs/use-immer/assets/20660062/cb2a4646-1dd9-4239-98e5-1ab5145e465c)
But when using this, I got no suggestion (tried ctrl+space || command + esc hotkey):
![image](https://github.com/immerjs/use-immer/assets/20660062/4065577f-1070-4b84-adf3-70b2f1fefadb)
I guess there is some problem with your typescript definition. But mannually import works just fine, but I prefer the auto flow(action on save feature in vscode).

**Comment by Wxh16144** [comment]
It looks like an editor or tsconfig configuration issue. I initialized a project with Vite and did not encounter the problem you described.

<img width="935" alt="image" src="https://github.com/immerjs/use-immer/assets/32004925/20481b50-1858-49e3-a4ba-7acd65393e0d">

**Comment by mweststrate** [comment]
Closing, we don't control this part of the IDE experience.
