### ISSUE TITLE
Updater called twice if two updaters are used in the same function

### ISSUE THREAD

**Issue by jennydaman** [immerjs/use-immer#139]
```jsx
import { useImmer } from "use-immer";

function App() {
  const [foo, setFoo] = useImmer([]);
  const [bar, setBar] = useImmer([]);

  const onClick = () => {
    // setFoo((draft) => { draft.push(1); });  // uncomment me
    console.count("onClick");
    setBar((draft) => {
      console.count("setBar");
    });
  };

  return <button onClick={onClick}>click me</button>;
}

export default App;
```

As expected, when the button is clicked, the console output is:

```
onClick: 1
setBar: 1
```

But if you uncomment the line which calls `setFoo`, the console output will be unexpected:

```
onClick: 1
setBar: 1
setBar: 2
```

Using React 18.3.1, use-immer 0.10.0, vite 5.4.8

**Comment by mweststrate** [comment]
Could you create a repo?

**Comment by jennydaman** [comment]
https://github.com/jennydaman/use-immer-twice-bug

**Comment by jennydaman** [comment]
Note that the actual state of `foo` and `bar` are correct, so this bug is only a problem if the updater given to `setBar` is impure.

**Comment by mweststrate** [comment]
Quick check, do you observe the same behavior when using useState instead?

**Comment by jennydaman** [comment]
Ah, it does happen with React.useState. I can also see that it is related to `React.StrictMode`. Sorry for the false alarm!
