### ISSUE TITLE
Automatically convert types?

### ISSUE THREAD

**Issue by corysimmons** [immerjs/use-immer#26]
I'd love it if I could get rid of the `if (e.target.type === 'number')` check: https://codesandbox.io/s/useimmer-demo-5ulb7

Sidenote: It would also be super amazing/ideal if I could get rid of the `e.persist()` 😍

**Comment by mweststrate** [comment]
You wish React to work differently. But that all seems completely out of
scope for useImmer :)

**Comment by corysimmons** [comment]
I think maintaining types could/should be in scope for Immer. I think you're right about `e.persist()` not being in scope of Immer, though.

**Comment by mweststrate** [comment]
Sorry, I really don't get what the type of `e.target.type` has to do with immer, `e` is coming from react, not immer.

**Comment by corysimmons** [comment]
Yeah you're 100% right now that I look at it closer.

https://codesandbox.io/s/browser-weirdness-number-input-value-is-a-string-6eikv

Seems like browsers pass `e.target.value` as a string no matter what.

💀 Sorry for wasting your time.
