### ISSUE TITLE
Type Definitons: React.useState can be initialized by factory function while useImmer can not

### ISSUE THREAD

**Issue by gnaeus** [immerjs/use-immer#27]
Since `useImmer()` is a tiny wrapper around native `useState()` it's initial value can be defined by factory function:

```ts
const [state] = useImmer(() => ({
  foo: 123
}));
```

But inferred type of `state` is `() => { foo: number; }` instead of `{ foo: number; }`.  
Because signature of `React.useState()` has overloading for this case:

```ts
function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<S>>];
```
While `useImmer()` signature accepts only raw state object:

```ts
function useImmer<S = any>(initialValue: S ): [S, (f: (draft: Draft<S>) => void | S) => void];
```

**Comment by mweststrate** [comment]
PR welcome

Op do 18 jul. 2019 17:13 schreef Dmitry Panyushkin <notifications@github.com
