### ISSUE TITLE
When using a class with constructor, immer does not detect changes

### ISSUE THREAD

**Issue by lucax88x** [immerjs/use-immer#31]
Hi guys, I don't know if this is a bug, but if it isn't, should be documented somewhere.

repro case:

https://stackblitz.com/edit/react-ts-qigunm

TLDR:

if you have class in the state, if this class has a constructor, and you pass values to it, when you try to modify a property of it on the reducer,  immer does not detect that the property as changed, therefore does not trigger a rerender of the component and it stays the same value forever,

infos:
- if you don't use constructor, and just create a plain object, it works.
- if you still keep the constructor, and you do not pass values to it, it works!
- with empty constructor, and you still pass values, it works
- I tried using useReducer, and then passing the a reducer with produce, so I could pass a PatchListener to log updates, and yeah, it does not log any change

Help.

ps: let me know if I should address this one on the immer repository..

**Comment by lucax88x** [comment]
https://stackoverflow.com/questions/47672518/typescript-getownpropertynames-constructor-properties-vs-getter-setter

REALLY?

Could be the cause?

**Comment by mweststrate** [comment]
Please read the readme first on how to use immer with classes.

Op wo 14 aug. 2019 11:11 schreef Luca Trazzi <notifications@github.com>:

**Comment by lucax88x** [comment]
Ok, I can burn myself.

I'll close it, I hope at least it can help some poor guy like me in the web struggling with the same.

Thanks.
