### ISSUE TITLE
Support immer ^4.x.x

### ISSUE THREAD

**Issue by JustFly1984** [immerjs/use-immer#33]
I see errors while updating my project since I've updated immer to 4.0.0
although everything works without issues

Thank you for your work!

**Comment by mweststrate** [comment]
Please be a bit more descriptive

Op zo 15 sep. 2019 22:43 schreef Alexey Lyakhov <notifications@github.com>:

**Comment by JustFly1984** [comment]
please update your peer dependencies to "immer": "^4.0.0"

**Comment by FredyC** [comment]
@JustFly1984 Peer dependency is about warning only during Yarn/NPM install. It's up to you update that in your project. If you are annoyed by warning, then submit a PR 😆

**Comment by JustFly1984** [comment]
10:07:02 PM: warning " > use-immer@0.3.3" has incorrect peer dependency "immer@^2.0.0 || ^3.0.0".

**Comment by FredyC** [comment]
Sorry, but it's fairly silly. You open this issue like some catastrophic errors are happening... 😆 

We have so many peer deps warnings in projects that we stopped worrying about those. Most of them are false positive of a wrong system. So it makes me smile every time when someone is concerned by the extra warning 😄

**Comment by mweststrate** [comment]
This is indeed a valid issue, thanks for the PR @nappy !

**Comment by mweststrate** [comment]
Should be released as 0.3.3 now
