### ISSUE TITLE
Updating an array

### ISSUE THREAD

**Issue by lexith** [immerjs/use-immer#40]
Hello, i'm currently pretty new to immer as well as react hooks and currently refactoring a bit of code.
I got a little trouble with updating an array.

Imagine a wrapper component that is only there to fetch some data and show another component after the fetching is complete, while showing some loading view during fetching.

```
function MyWrapper() {
	const [data, updateData] = useImmer([]);

	useEffect(() => {
		preFetch();
	}, []);

	function preFetch() {
		try {
			Promise.all([
				axios.get('https://jsonplaceholder.typicode.com/users'),
				new Promise(resolve => {
					setTimeout(() => {
						resolve();
					}, 1000);
				})
			]).then(([response]) => {
				if (response && response.data) {
					updateData(draft => {
						draft.data = response.data
					});
				}
			});
		} catch (error) {
			console.log('Error catched', error);
		}
	}

	return data ? <MyList data={data} /> : <MyLoader/>;
    }
```

I expected this to work, but i get an error message: 

> immer.module.js:930 Uncaught Error: Immer only supports setting array indices and the 'length' property
    at Object.arrayTraps.set (immer.module.js:930)

After a lot of trial and error i found these two approaches to work: 

```
updateData(() => { 
    return response.data;
})
```

```
updateData(draft => (draft = draft.concat(response.data)));
```

which worked for me, but i don't see why the first approach doesn't. I also tried it using `produce` directly instead of `useImmer` like so:

```
const [data, updateData] = useState([]);

// ...

function preFetch() {
// ...
updateData(
    produce(draft => {
		draft.data = response.data;
    })
);
}
```

with the same outcome.

Any help would be greatly appreciated.

P.S: Would it be considered bad practice to replace an entire array (even if it's an empty one like in this example?) and therefore should go with the `concat` approach?

**Comment by FredyC** [comment]
I don't think you should be doing `draft.data` because you have an array directly as a state. It would need to be `useImmer({ data: [] })` to work like you have.

**Comment by lexith** [comment]
> I don't think you should be doing `draft.data` because you have an array directly as a state. It would need to be `useImmer({ data: [] })` to work like you have. Or work directly with `draft` as the array, although I am not sure if that works.

Aww man, yeah the error completely makes sense now. before using hooks, `draft` in `produce()` was always the whole state. Now what i did is totally wrong because i refactored my HOCs to functional components using hooks and immer at the same time and tried to implement it in a way as if i would still get the whole state (which holds my data array). But with the hooks i get my data array directly. I'm an idiot. Thanks. That just cleared my confusion.

**Comment by FredyC** [comment]
One of the reasons why I love TypeScript, errors like that would scream at me right away :)
