### ISSUE TITLE
How to avoid the problem come from `capture value` of function component?

### ISSUE THREAD

**Issue by zmayor** [immerjs/use-immer#41]
[reproduction](https://codesandbox.io/s/useimmer-capture-value-541ro)

`use-immer` is really helpful. But I don't know what to do to solve the `capture value` problem.

Look at the reproduction, when I click the add button, the value changed. But the `print` method just printed the old value. How to avoid this problem?

**Comment by mweststrate** [comment]
In react state is only visible _after_ it has been rendered. So if you have
side effects that should see the state, you should call using useEffect,
.e.g `useEffect(() => { print(state.value }, [state.value])`
