### ISSUE TITLE
Cannot perform 'get' on a proxy that has been revoked

### ISSUE THREAD

**Issue by sergej-s** [immerjs/use-immer#43]
Hello!

Im getting the error `Cannot perform 'get' on a proxy that has been revoked` in jest tests.
You can find the error reproduced here https://codesandbox.io/s/old-platform-yeq09
In browser everything works like a charm. Only test fails. Maybe Im missing something.
Could you help?

**Comment by FredyC** [comment]
You shouldn't be passing draft outside of `setState`, that's equal to memory leak. Get some inspiration in #41.

**Comment by sergej-s** [comment]
@FredyC I see! Although useEffect makes code more convoluted but it works. Many thanks! 👍

**Comment by FredyC** [comment]
@sergej-s The other alternative would use `produce` of `immer` directly and you can pass return value of that call to onClick just fine.
