### ISSUE TITLE
useImmer with maps

### ISSUE THREAD

**Issue by Reiiya** [immerjs/use-immer#49]
This code below does not seem to be working.

```
const [state, setState] = useImmer<Map<string, object>>(new Map());

const addToMap = (key: string, val: object) => {
    setState((draft) => {
        draft.set(key, val)
    })
}
```

It does not seem to be creating a new reference. Its also not stated anywhere, is this Immer version compatable with maps?

**Comment by mweststrate** [comment]
Can you create a small reproduction in codesandbox?

Op wo 1 apr. 2020 08:38 schreef Reiiya <notifications@github.com>:

**Comment by mweststrate** [comment]
Closing and referring to https://immerjs.github.io/immer/docs/complex-objects without any further info
