### ISSUE TITLE
Support recursive immer

### ISSUE THREAD

**Issue by benlesh** [immerjs/use-immer#54]
My apologies if this is already handled. I'm digging through a codebase at work and I saw a comment that we had a custom hook to add recursive immer handling to use-immer.

I just wanted to capture this here so I can link the issue in the code, and we have somewhere to track it.

Here is the comment and the code in question:

```ts
// The built-in useImmer doesn't support recursively calling the
// update function, e.g. updateFoo(draft => { updateFoo(draft => {}); });
// It only applies the last update. This wraps things so that it does,
// but ideally we'd fix this problem in use-immer itself via PR.
// TODO: Fix upstream in use-immer
function useRecursiveImmer<T>(initialValue: T) {
  const [value, updateValue] = useImmer<T>(initialValue);
  let isUpdating = false;
  let draft: Draft<T> | null = null;

  const updateValueRecursive: typeof updateValue = (callback) => {
    if (isUpdating && draft) {
      callback(draft);
    } else {
      isUpdating = true;
      updateValue((_draft) => {
        draft = _draft;
        callback(draft);
        isUpdating = false;
        draft = null;
      });
    }
  };

  // Needs to be seen as a tuple, not an array
  return [value, updateValueRecursive] as [typeof value, typeof updateValue];
}
```

Again, apologies if this is something that has already been addressed, it's not something I'm focused on at the moment. Just trying to be a good citizen.

Hope all is well!

**Comment by mweststrate** [comment]
@benlesh I'm doing well, thanks! Sorry for the late follow up! It looks a bit funny / as a hook violation to me if `useImmer` (either the hook itself or the updater) is called recursively again from the updater function. It would be great if a small code sandbox could be made with a simple example demonstrating what problem the example above solves.
