### ISSUE TITLE
在useEffect中修改Set类型的state时，为什么要手动执行enableMapSet来允许呢？

### ISSUE THREAD

**Issue by Highnesslin** [immerjs/use-immer#56]
`
const [state, setState] = useImmer<TabState>({
    listSet: new Set([])
});

useEffect(() => {
      setState(state => {
        state.listSet.add(activeRouteId);
      });
}, [activeKey]);
`
`
Error: [Immer] The plugin for 'MapSet' has not been loaded into Immer. To enable the plugin, import and call `enableMapSet()` when initializing your application.`

**Comment by mweststrate** [comment]
import and call enableMapSet() from Immer when initializing your
application.
