### ISSUE TITLE
Update by reference (like MST/Mobx)

### ISSUE THREAD

**Issue by andraz-at** [immerjs/use-immer#62]
I want to update an element in a table by passing a reference to it via props.

In MST this works without a problem, you pass the reference,  there are actions on the reference, which update the data in the right place.

How to do something similar (update via reference) with use-immer?

My current solution using indexes and referencing the root directly is the oldschool dirty solution which is exactly what I wish to avoid as it will not scale when those objects get arrays/maps of nested objects with their own nested arrays etc... with each level having its own component.

```javascript
<div>
{store.conditions.all.map((c, i) => {
          const setName = name =>
            setStore(s => {
              // how to replace this with
              // c.name = name
              // using only c ref inside the <Condition /> ?
              s.conditions.all[i].name = name
            })

          const remove = () =>
            setStore(s => {
              s.conditions.all.splice(i, 1)
            })

          return (
            <Condition
              index={i}
              key={i}
              condition={c}
              remove={remove}
              setName={setName}
            />
          )
        })}
</div>
```

https://codesandbox.io/s/use-immer-example-ekhj9?file=/src/App.js

**Comment by mweststrate** [comment]
In the immutable data tree paradigm there is no safe concept of reference
you can safely hold on to to perform updates on, you will have to remember
for example an external key and find it back from the original root. That
kind of behavior can be standardized by using lenses / cursors (look up an
item back from the root later in the future), but that is further not in
the scope of immer and can be done by libraries like rambda.

**Comment by andraz-at** [comment]
So map of objects + lookup from a global central store by id, similar to what I was doing in MST before...

Does immer accept hooking functions onto objects (aka passing a function ref around which wrapped a closure around the context) or would that working just be an unexpected side effect, which we should avoid because of memory leaks or other dangers?

**Comment by mweststrate** [comment]
Sound mostly like something that would be confusing to me. But... try it?
