### ISSUE TITLE
Returning `nothing` in updater fails typescript compilation

### ISSUE THREAD

**Issue by aeons** [immerjs/use-immer#63]
Per https://immerjs.github.io/immer/docs/return#producing-undefined-using-nothing, you can return the constant `nothing` to set a draft to `undefined`.

This fails when using `useImmer`, with `Type 'Nothing' is not assignable to type 'void | T | undefined'.`

I suspect the machinery for `nothing` is just missing from the types in this repo.

**Comment by mweststrate** [comment]
Fixed in 0.5.1
