### ISSUE TITLE
Typescript error on Generics Reducer

### ISSUE THREAD

**Issue by sonatard** [immerjs/use-immer#64]
This code can execute but it has an error on the reducer.

https://codesandbox.io/s/custom-hook-v71-9pqu0?file=/src/useStack.ts

<img width="686" alt="error log" src="https://user-images.githubusercontent.com/1586910/91932017-ffd2de00-ed1f-11ea-9d1d-0f129234aaf7.png">

Removing the generics will remove the error.

https://codesandbox.io/s/custom-hook-v72-forked-51k3h?file=/src/useStack.ts

How can I fix it?

**Comment by mweststrate** [comment]
The reproduction doesn't seem to reflect the question. For the original problem, passing the generic to immerReducer might help: `useImmerReducer<StackState<T>>(stackReducer())`
