### ISSUE TITLE
using updateState method in hook requires updateState method as a dependency ?

### ISSUE THREAD

**Issue by jiangyh1024** [immerjs/use-immer#67]
using useState will not require it to be a dependency 

is there any way to avoid this warning??

or do I have to include the updateState  method to the dependency array?

![image](https://user-images.githubusercontent.com/34930870/97148124-8dbdc900-17a5-11eb-91ac-e0fc2e54eb8b.png)

![image](https://user-images.githubusercontent.com/34930870/97147993-5b13d080-17a5-11eb-99a1-1a59e76b3ed7.png)

**Comment by mweststrate** [comment]
yes, just include it in de dep array. The ref is stable but React / lint
doesn't know that (unlike setState which is a hardcoded exception)

**Comment by jiangyh1024** [comment]
OK， thanks a lot
