### ISSUE TITLE
Missing support for React 17.0.1

### ISSUE THREAD

**Issue by LuigiElleBalotta** [immerjs/use-immer#68]
Hello,
I was trying to install immer into a NextJS project, I get this error: 

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: thebarani@0.1.0
> npm ERR! Found: react@17.0.1
> npm ERR! node_modules/react
> npm ERR!   react@"17.0.1" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.8.0" from use-immer@0.4.1
> npm ERR! node_modules/use-immer
> npm ERR!   use-immer@"0.4.1" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /Users/sviluppo/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/sviluppo/.npm/_logs/2020-11-03T11_02_44_185Z-debug.log

LOG FILE: https://pastebin.com/4wRQDs9b

**Comment by FredyC** [comment]
You can surely contribute a PR, that's easy enough and it's the fastest way.

I am honestly surprised that NPM is so strict to fail on peer deps.

**Comment by mweststrate** [comment]
Fixed in 0.4.2
