### ISSUE TITLE
ESLint no-void warnings

### ISSUE THREAD

**Issue by KasimAhmic** [immerjs/use-immer#80]
When using a library like [standard](https://standardjs.com/) that uses ESLint under the hood, you'll probably see errors thrown regarding the use of `void` in Immer Reducers thanks to [the no-void rule](https://eslint.org/docs/2.0.0/rules/no-void).

e.x.
```powershell
PS ...> npx semistandard --fix
semistandard: Semicolons For All! (https://github.com/standard/semistandard)
  .\src\Context.js:47:7: Expected 'undefined' and instead saw 'void'.
  .\src\Context.js:48:7: Expected 'undefined' and instead saw 'void'.
  .\src\Context.js:49:7: Expected 'undefined' and instead saw 'void'.
```

In general, this isn't an issue as in the ESLint config you could just disable the rule or add `/* eslint-disable no-void */` to the top of whatever file you're using `void` in. I'm not a fan of either of these solutions so instead, I've been writing my Immer Reducers like so:

```javascript
export const globalImmerReducer = (state, action, update = () => {}) => {
  switch (action.type) {
    case actionTypes.SET_VALUE:
      update(state.number = action.value);
      update(state.numberString = action.value.toString());

      return;

    case actionTypes.SOME_ACTION:
      return update(state.someState= action.someValue);

    default:
      return console.warn(`Unknown action type: ${action.type}`);
  }
};
```

The use of the no return `update()` function is the key here since it really just emulates the behavior of `void`. This has been working fine for me for some time and have not noticed any issue whatsoever but I still wanted to make sure this was alright before I start pushing this stuff out to production.

1. Is this a valid approach?
2. Are there any side effects I should be on the lookout for?
3. Should this be included in the README as either the default approach or in a "if you use ESLint..." section?

**Comment by KasimAhmic** [comment]
Actually, maybe I completely misunderstood the useImmerReducer hook. I just tried to remove my update function, didn't replace it with `void`, and everything still worked just fine.

```javascript
export const globalImmerReducer = (state, action) => {
  switch (action.type) {
    case actionTypes.SET_VALUE:
      state.number = action.value;
      state.numberString = action.value.toString();
      break;

    case actionTypes.SOME_ACTION:
      state.someState= action.someValue;
      break;

    default:
      console.warn(`Unknown action type: ${action.type}`);
  }
};
```

Am I missing something here or has there been a change that isn't reflected in the useImmerReducer example in README.md?

**Comment by mweststrate** [comment]
I think I've never seen the thing you did in the first comment, I don't think that came from this package? So yeah the second approach looks fine to me.

**Comment by KasimAhmic** [comment]
> I think I've never seen the thing you did in the first comment, I don't think that came from this package? So yeah the second approach looks fine to me. 

Yeah, that was me just trying to get rid of the void keyword in the reducer. Think I just misinterpreted the use of it in the useImmerReducer example in the README.

Thanks for the feedback!
