### ISSUE TITLE
Can you folks push up the code/tags for the 0.5.2 release?

### ISSUE THREAD

**Issue by Kobold** [immerjs/use-immer#89]
Thanks for maintaining use-immer! It and the whole ecosystem are great.

I'm trying to understand what's in the 0.5.2 release on NPM [1], but it looks like the last code that was pushed up here was for 0.5.1. I could download the package from NPM and diff it, but it would be great just to be able to look at it in Github.

A second ask, if easy, is can you push up git tags for the 0.5.x release series? No problem though if that's not easy.

[1] https://www.npmjs.com/package/use-immer

**Comment by mweststrate** [comment]
Everything should be pushed now
