### ISSUE TITLE
Attempted import error: 'freeze' is not exported from 'immer' (imported as 'r').

### ISSUE THREAD

**Issue by libin1991** [immerjs/use-immer#97]
```
index.js:1437 ./node_modules/_use-immer@0.6.0@use-immer/dist/use-immer.module.js
Attempted import error: 'freeze' is not exported from 'immer' (imported as 'r').
 ```

**Comment by mweststrate** [comment]
Reproduction etc plz

**Comment by zzlzm** [comment]
Same problem +1, downgrade to version 0.5.2 solved

**Comment by lzlandyezi1116** [comment]
Demoted to version 0.5.2, but it didn't work for me, and the problem continued.

**Comment by citrusjunoss** [comment]
+1

**Comment by Evanl-lai** [comment]
So the problem is still unresolved. Please

**Comment by citrusjunoss** [comment]
other package depend low version of Immer,  update immer reslove this error for me

**Comment by mweststrate** [comment]
This is not a bug in the package but in your project setup. Please make
sure peer dependencies are satisfied or provide a reproduction. Further
just +1-ing on this issue is pointless.

**Comment by epranka** [comment]
Try to install "immer"

**Comment by TotooriaHyperion** [comment]
fixed by https://github.com/immerjs/use-immer/pull/131 on Jun 11, 2024
